version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  sqlpad:
    image: sqlpad/sqlpad:latest
    ports:
      - '4000:3000'
    environment:
      - SQLPAD_ADMIN=admin
      - SQLPAD_ADMIN_PASSWORD=admin
      - SQLPAD_SEED_DATA_PATH=/etc/sqlpad/seed-data
      - SQLPAD_CONNECTIONS__pgdemo__name=eufron DB
      - SQLPAD_CONNECTIONS__pgdemo__driver=postgres
      - SQLPAD_CONNECTIONS__pgdemo__host=db
      - SQLPAD_CONNECTIONS__pgdemo__database=postgres
      - SQLPAD_CONNECTIONS__pgdemo__username=postgres
      - SQLPAD_CONNECTIONS__pgdemo__password=postgres
    restart: always

volumes:
  db:
    driver: local
