# Generated by Django 4.1.7 on 2023-03-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='username'),
        ),
    ]
